### ISSUE TITLE
Please provide a minimal working example that use ASSIGN section in module

### ISSUE THREAD

**Issue by MatthieuPERIN** [sbusard/pynusmv#4]
Hi,

I try to model a simple automaton that use ASSIGN section: 

``` python
from pynusmv.model import *


class main(Module):

    Q = Var(Boolean(), "Q")

    INIT = [(Q == Falseexp())]

    ASSIGN = {Next("Q"), ~Q}

print(main)
```

But so far I obtain an error:

``` shell
Traceback (most recent call last):
  File "test_pynusmv.py", line 8, in <module>
    class main(Module):
  File "/home/perinm/Git/pynusmv/src/pynusmv/model.py", line 2225, in __new__
    internal = mcs._section_internal(member, namespace[member])
  File "/home/perinm/Git/pynusmv/src/pynusmv/model.py", line 2413, in _section_internal
    key, value = line[0:2]
ValueError: too many values to unpack (expected 2)
```

The use of other ASSIGN:

``` python
    ASSIGN = {Next(Q), ~Q}
```

Bring the same error.

Please provide a working example of an use of ASSIGN section so that I can correct mine !

**Comment by MatthieuPERIN** [comment]
My bad, the grammar is incorrect in Python.
